[config]
schemaVersion = "0.0.1"

[general]
repository = "https://github.com/wwwDayDream/Fragile"

[package]
namespace = "www_Day_Dream"
name = "Fragile"
description = "Makes your body fragile. Be careful not to fall over!"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "TS.README.md"
outdir = "../dist"

[[build.copy]]
source = "../bin/Release/netstandard2.1/Fragile.dll"
target = "/BepInEx/plugins/Fragile/"

[publish]
communities = [ "content-warning" ]
[publish.categories]
content-warning = [ "mods" ]
# For a list of valid tags, look at the slug values in https://thunderstore.io/api/experimental/community/content-warning/category/
